### ISSUE TITLE
name clash with xinitrc86/zthread

### ISSUE THREAD

**Issue by larshp** [abapify/assert#6]
see https://github.com/dotabap/dotabap-list/actions/runs/10158696201/job/28091310476

suggest renaming and/or prefixing

```
Duplicate filename, xinitrc86/zthread: zcl_assert.clas.abap
Duplicate filename, xinitrc86/zthread: zcl_assert.clas.xml
```

also see https://github.com/xinitrc86/zthread/issues/1

**Comment by ThePlenkov** [comment]
i can try to rename.

**Comment by ThePlenkov** [comment]
i had to rename completely ( and also a bit reworked ). Now is zcl_assetable

**Comment by ThePlenkov** [comment]
@larshp  could you please try new name? I still need to update dependent projects

**Comment by larshp** [comment]
success, https://github.com/dotabap/dotabap-list/actions

**Comment by larshp** [comment]
![image](https://github.com/user-attachments/assets/7efa4dde-05e0-4dcd-ab42-924addcc70dc)

**Comment by ThePlenkov** [comment]
i need to create better icon =) thanks
